notifications:
  email:
    on_success: never
    on_failure: change

dist: trusty

sudo: false

os: linux
compiler: clang

env:
  - CC=clang CXX=clang++ npm_config_clang=1

addons:
  apt:
    packages:
      # this is required to compile keytar
      - libsecret-1-dev
      # this package is essential for testing Electron in a headless fashion
      # https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md
      - xvfb
      # packages required for electron-installer-debian
      - fakeroot
      - dpkg
      # packages required for electron-installer-redhat
      - rpm
      # packages required for electron-installer-appimage
      - xz-utils
      - xorriso
      - zsync

branches:
  only:
    - master
    - /^__release-.*/

language: node_js
node_js:
  - '8.12'

cache:
  yarn: true
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron
    - .eslintcache
    - $HOME/.cache/electron-builder

install:
  - yarn install --force

script:
  - yarn lint && yarn validate-changelog && yarn build:prod && yarn test:setup
    && yarn test && yarn test:report

after_failure:
  - yarn test:review
