notifications:
  email:
    on_success: never
    on_failure: change

os:
  - osx

branches:
  only:
    - master
    - /^__release-.*/

language: node_js
node_js:
  - "6"

cache:
  timeout: 600
  directories:
    - node_modules

install:
  - npm prune
  - cd app && npm prune && cd ..
  - npm install

script:
  - npm run lint
  - npm run build:prod
  - npm run test:setup
  - npm test

after_success:
  - npm run publish

after_failure:
  - npm run test:review
