os: Visual Studio 2015

platform:
  - x64

environment:
  nodejs_version: "7"

cache:
  - node_modules -> appveyor.yml
  - '%USERPROFILE%\.electron -> appveyor.yml'

branches:
  only:
    - master
    - /^__release-.*/

skip_tags: true

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm
  - git submodule update --init --recursive
  - npm prune
  - cd app && npm prune && cd ..
  - npm install

build_script:
  - npm run lint
  - npm run build:prod

test_script:
  - npm run test:setup
  - ./script/test-appveyor.bat

on_success:
  - npm run publish

on_finish:
  - npm run test:review
