os: Visual Studio 2015

platform:
  - x64

environment:
  nodejs_version: "8.7.0"

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

branches:
  only:
    - master
    - /^__release-.*/

skip_tags: true

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g yarn@1.2.1
  - git submodule update --init --recursive
  - yarn install --force

build_script:
  - yarn check-prettiness
  - yarn lint
  - yarn build:prod

test_script:
  - node --version
  - yarn test:setup
  - ./script/test-appveyor.bat

on_success:
  - yarn run publish

on_finish:
  - yarn test:review
