os: Visual Studio 2015

platform:
  - x64

environment:
  nodejs_version: "7"

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

skip_tags: true

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm@4.6.1
  - git submodule update --init --recursive
  - npm prune
  - cd app && npm prune && cd ..
  - npm install

build_script:
  - npm run lint

test_script:
  - node --version
  - npm --version
  - npm run test:setup
  - ./script/test-appveyor.bat

on_success:
  - npm run release

on_finish:
  - npm run test:review
