os: Visual Studio 2015

platform:
  - x64

environment:
  nodejs_version: "6"

cache:
  - node_modules -> appveyor.yml
  - '%USERPROFILE%\.electron -> appveyor.yml'

branches:
  only:
    - master
    - /^__release-.*/

skip_tags: true

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:PRIVATE_KEY.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
  - git submodule update --init --recursive
  - npm install

build_script:
  - npm run lint
  - npm run build:prod

test_script:
  - npm run test:setup
  - ./script/test-appveyor.bat

on_success:
  - npm run publish

on_finish:
  - npm run test:review
