os: Visual Studio 2015

platform:
  - x64

environment:
  nodejs_version: '8.12'

cache:
  - .eslintcache
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'

branches:
  only:
    - master
    - /^__release-.*/

skip_tags: true

version: '{build}'

install:
  - cmd: regedit /s script\default-to-tls12-on-appveyor.reg
  - ps: Install-Product node $env:nodejs_version $env:platform
  - git submodule update --init --recursive
  - yarn install --force

build_script:
  - yarn lint
  - yarn validate-changelog
  - yarn build:prod

test_script:
  - yarn test:setup
  - ./script/test-appveyor.bat
  - yarn test:report

on_success:
  - yarn run publish

on_finish:
  - yarn test:review
