os: Visual Studio 2015

platform:
  - x64

environment:
  nodejs_version: '10.17.0'

cache:
  - '%USERPROFILE%\.electron'
  - .eslintcache
  - '%LOCALAPPDATA%\Yarn\Cache\v4'

skip_tags: true
skip_branch_with_pr: true

version: '{build}'

install:
  - cmd: regedit /s script\default-to-tls12-on-appveyor.reg
  - ps: Install-Product node $env:nodejs_version $env:platform
  - git submodule update --init --recursive
  - yarn install --force

build_script:
  - yarn lint
  - yarn validate-changelog
  - yarn check-modified
  - yarn build:prod

test_script:
  - yarn test:setup
  - ./script/test-appveyor.bat

on_success:
  - yarn run publish

on_finish:
  - yarn test:review
  - yarn test:report
